name: CI Checks
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Copy binary to artifact directory
        run: |
          mkdir artifacts
          cp ./bin/lenslocked ./artifacts
      - name: Archive artifact directory
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts
