name: CI Checks
on:
  push:
    branches: [ main ]
jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Run tests
        run: task test

      - name: Coverage Check
        run: task coverage-check

      - name: Generate Report
        run: task generate-coverage-report

      - name: Archive reports directory
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: ./reports
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: task build

      - name: Copy binary to artifact directory
        run: |
          mkdir artifacts
          cp ./bin/lenslocked ./artifacts

      - name: Archive artifact directory
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts
